Cleaning pads interval (wash interval)
DeebotUniverse/Deebot-4-Home-Assistant pull request #483
Opened 2023-12-18 16:39 UTC by NEVdataDyne

Adds the option to set the interval between two washing of the clean pads.

2023-12-18 16:40 UTC, NEVdataDyne commented
I still encounter an issue that I can't solve and need the help from someone who knows how to correct it, I don't know if the problem is in this code or the client (see https://github.com/DeebotUniverse/client.py/pull/376 )

2023-12-18 18:55 UTC, edenhaus requested changes

2023-12-18 18:55 UTC, edenhaus commented on custom_components/deebot/manifest.json
> +    "git+https://github.com/NEVdataDyne/client.py.git@dev#deebot-client==4.0.0dev0",
Please revert this line

2023-12-18 20:28 UTC, NEVdataDyne commented
Tested successfully in HA

2024-02-16 17:11 UTC, edenhaus commented
As this component was migrated directly to HA core, please open the PR in https://github.com/home-assistant/core. Please note that the component is called `ecovacs` in the core repo

I will close it here as no features will be accepted for the custom component.

2024-02-16 17:11 UTC, closed without merging

2024-02-18 12:07 UTC, NEVdataDyne commented
@edenhaus : I made this development by copying what had been done for the cleaning mode option and with your help and MVladislav's help. I have no idea what I need to do to replicate this in HA core.

Could you please advise what I should do?

2024-02-19 07:50 UTC, edenhaus commented
First, wait until the client PR is merged, and then you only need to apply the Number change to the core repo